@startuml project-diagram.puml

allowmixing

package "Estruturas"{
    class OrderList <<struct>>{
        +Node* head
        +int size
        +void addOrder(Node order)
        +void removeOrder(int orderId)
        +void listPendentOrders()
    }

    class OrderQueue <<struct>>{
        +Node* front
        +Node* rear
        +int count
        +void enqueue(Node order)
        +Node dequeue()
        +void processOrder()
        +void listProcessingOrders()
    }

    class Node <<struct>>{
        +int orderId
        +char customerName[50]
        +Node* next
    }
}

package "CLI - Telas" {
    rectangle "Menu\n1 - Adicionar pedido\n2 - Remover pedido\n3 - Processar pedido\n4 - Listar pedidos (Salão)\n5 - Listar pedidos (Cozinha)" as homeScreen

    rectangle "Pratos\n1 - Entradas\n2 - Pratos Principais\n3 - Sobremesas" as platesScreen

    rectangle "Entradas\n1 - Sopa de Cebola\n2 - Salada Caesar\n3 - Bruschetta\n4 - Carpaccio de Carne\n5 - Camarão ao Alho" as appetizersScreen

    rectangle "Pratos Principais\n1 - Lasanha à Bolonhesa\n2 - Filé Mignon com Fritas\n3 - Frango Grelhado com Legumes\n4 - Bacalhau à Gomes de Sá\n5 - Risoto de Cogumelos" as mainPlates

    rectangle "Sobremesas\n1 - Tiramisu\n2 - Cheesecake de Frutas Vermelhas\n3 - Mousse de Chocolate\n4 - Pudim de Leite\n5 - Sorvete de Baunilha com Calda de Morango" as dessertsScreen
}

homeScreen --> platesScreen : 1
platesScreen --> appetizersScreen : 1
platesScreen --> mainPlates : 2
platesScreen --> dessertsScreen : 3

@enduml